human_perception:
  robot_tracker:
    # Parameters for robot_track_publisher.cpp
    ros_parameters:
      odom_topic: "/zed2/zed_node/odom"
      robot_track_topic: "/robot/ego_trajectory"
      pub_frame_id: "map"
      pub_frame_rate: 15.0
      max_history_length: 12
      max_interp_interval: 0.4
    